### ISSUE TITLE
Can't translate the "Log in with Twitter" text

### ISSUE THREAD

**Issue by Igormandello** [affinitweet/translations#21]
At the top of the Landing page, we have this "Log In" button:
![image](https://user-images.githubusercontent.com/19190744/51878584-4fd50c00-2357-11e9-973c-030a35763538.png)

After we hover it, the text changes to "Log In with Twitter":
![image](https://user-images.githubusercontent.com/19190744/51878505-0edcf780-2357-11e9-9ed1-9a16d2afd61b.png)

Neither the "Log In" nor the "Log In with Twitter" texts are present in the translation file, so they can't be translated. It would be nice to translate this text, for a more complete translation.

**Comment by HapLifeMan** [comment]
Hi @Igormandello, thanks for your suggestion!
I know that's the only text not translatable and this is because there's a technical problem related.
I will reconsider it and keep you updated 🙂

**Comment by Igormandello** [comment]
Thanks @HapLifeMan!
I'm working on the pt-br translation and the respective texts in Portuguese are: "Entrar" and "Entrar com o Twitter", so they're perfectly suitable to this animation, but I think in some languages this feature isn't possible, due to the placement of their nouns and verbs placements in the sentence. So I would recommend some way to "turn off animation" when the translator deems it necessary.

**Comment by HapLifeMan** [comment]
Oh amazing! Thank you for your help 😊

I'm actually rewriting Affinitweet in order to improve the SEO.
So I will made an update by the end of the month or during March!

There will be no additional translations, so if you want to submit your own when they're ready and even if "Entrar" and "Entrar com o Twitter" are missing, it's ok, I would add them for you 🙂

**Comment by Igormandello** [comment]
Thanks again! As soon as I finish my translations, I'll be opening a PR

Good luck man, amazing work 🙂
