### ISSUE TITLE
I'm translating to Brazilian Portuguese

### ISSUE THREAD

**Issue by williansimao** [affinitweet/translations#22]
It will be done in two or three days

**Comment by HapLifeMan** [comment]
Hey @williansimao! Thank you for your help, a [Portuguese translation](https://github.com/Igormandello/translations) is already in process by @Igormandello, you can maybe help him 😊

**Comment by Igormandello** [comment]
Hi @williansimao (eae mano), I have already "finished" the pt-br translations, the only thing left is the Legal section, kinda boring haha, but you could take a look at my translations and fixes some typos or suggest some changes  :)

**Comment by Igormandello** [comment]
btw @HapLifeMan, I don't know if it's a good idea translate the legal, privacy and terms of service sections, there are so many ambiguities that could be created in this process, anyway, if yo want, I could open the pt-br translation PR without these sections and add them (or someone else this) later.

**Comment by williansimao** [comment]
arrasou então
