### ISSUE TITLE
Add translation to Filipino/Tagalog language

### ISSUE THREAD

**Issue by Cyyy1998** [affinitweet/translations#9]

**Comment by HapLifeMan** [comment]
Hi @Cyyy1998, feel free to send a pull request with these translations, I'll merge it once finished :)

**Comment by Cyyy1998** [comment]
Theres Filipino translation already . Can i translate it to Cebuano ?

**Comment by HapLifeMan** [comment]
Of course feel free to translate and send a PR.
Please use the english translation to be as accurate as possible!
